name: Flutter Build APK

on:
  push:
    branches: ['main', 'master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      # 1. فك التشفير للمفتاح الرقمي (للتوقيع)
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      # 2. بناء التطبيق (مع المفاتيح السرية والتوقيع)
      - name: Build APK
        run: |
          flutter build apk --release \
            --dart-define=GROQ_API_KEY=${{ secrets.MY_GROQ_ID }} \
            --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --dart-define=SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          STORE_FILE: 'upload-keystore.jks'

      # 3. رفع الـ APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: summify-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
